edition: global.edition.community
version: v0.6.3

mongo:
  host: localhost
  port: 27017
  db: crawlab_test
  username: ""
  password: ""
  authSource: "admin"

server:
  host: 0.0.0.0
  port: 8000

grpc:
  address: 127.0.0.1:9666
  server:
    address: 127.0.0.1:9666
  authKey: Crawlab2021!

api:
  endpoint: http://localhost:8000

node:
  type: master

result:
  enabled: true